/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zhc_others_MySystem */

#ifndef _Included_zhc_others_MySystem
#define _Included_zhc_others_MySystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zhc_others_MySystem
 * Method:    setOut
 * Signature: (Ljava/io/PrintStream;)V
 */
JNIEXPORT void JNICALL Java_zhc_others_MySystem_setOut
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
